name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

        # Deploy the Static Site to Public Repo (GitHub Pages)
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token:  ${{ secrets.SUBMODULE_CONTENT_DEPLOY_KEY }}
          repository-name: send2manoo/test-blog
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
          single-commit: true
          commit-message: "Deployment from source send2manoo/submodule on OCT 30 13:24 PM"
